name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload Binary
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          
      - name: Rename binary
        run: mv target/release/Blog-Creator ${GITHUB_REPOSITORY##*/}-linux-x86_64
        
      - name: Upload binary to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${GITHUB_REPOSITORY##*/}-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
